name: Deploy to GitHub Pages via angular-cli-ghpages

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
      - name: Percy Test
        run: npx percy exec -- serve-and-run-cy 
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}